version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"  # Corrected port mapping
    volumes:
      - .:/app  # Mounting the current directory to /app in the container
    links:
      - db:db

    depends_on:
      - db
    networks:
      - my_network

  db:
    image: postgres
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=shubham
      - POSTGRES_PASSWORD=shubham123 
    ports:
      - "5432:5432"
    
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
